// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi Tingting
Tingting


    Schemes:
      http
      https
    Host: virtserver.swaggerhub.com
    BasePath: /nanjingyouzi/tingting/1.0.0
    Version: 1.0.0
    Contact: <64060764@qq.com>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
